### ISSUE TITLE
Does not work when the file path contains spaces 

### ISSUE THREAD

**Issue by logonoff** [NoahSyn10/VSCode-PyDoctestBtn#5]
Using extension verison `v1.0.3` and vscode `1.60.1`

log output while running:

```C:\ProgramData\scoop\apps\python\current\python.exe -m doctest -v c:\Users\logonoff\Desktop\i am a folder with spaces\python.py
Traceback (most recent call last):
  File "C:\ProgramData\scoop\apps\python\current\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\scoop\apps\python\current\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\scoop\apps\python\current\lib\doctest.py", line 2793, in <module>
    sys.exit(_test())
  File "C:\ProgramData\scoop\apps\python\current\lib\doctest.py", line 2785, in _test
    failures, _ = testfile(filename, module_relative=False,
  File "C:\ProgramData\scoop\apps\python\current\lib\doctest.py", line 2055, in testfile
    text, filename = _load_testfile(filename, package, module_relative,
  File "C:\ProgramData\scoop\apps\python\current\lib\doctest.py", line 232, in _load_testfile
    with open(filename, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\logonoff\\Desktop\\i'
```

Seems to work when I put quotes around the path to be tested though.

**Comment by NoahSyn10** [comment]
I'll look into that as soon as I get a chance, I think adding quotations when a space is present should do the trick, I had not considered that case. Thank you for your feedback!

**Comment by NoahSyn10** [comment]
Sorry about the major delays, I'm glad I finally got to it. Filenames are now surrounded by quotations when running the doctest command with the button.
